CREATE TABLE `cars`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`Image_URL` VARCHAR(500),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`Mileage` BIGINT,
	`model` VARCHAR(100),
	`Price` VARCHAR(50),
	`SoftDeleteFlag` BOOLEAN,
	`Year` BIGINT,
	PRIMARY KEY(`id`)
);
ALTER TABLE `cars`
	ADD CONSTRAINT `63dd0b5927898be37c26d1297552be` UNIQUE KEY(`id`);
